### ISSUE TITLE
Premature container disposal

### ISSUE THREAD

**Issue by mrchris2000** [tdomzal/junit-docker-rule#26]
Encountering an odd issue with this rule on our project.
For the MQLight container ( https://developer.ibm.com/messaging/2015/02/11/introducting-docker-mqlight/ ), I see the container shut down before the test case has completed.

If you get a chance the issue can be reproduced by running:
miniature-queue\mqlight\src\test\java\com\github\mrchris2000\queue\mqlight\example\FanoutTest.java

The repository is : https://github.com/mrchris2000/miniature-queue

This should be self contained enough for a simple reproduction.
Any clues as to the problem are greatly appreciated.

**Comment by tdomzal** [comment]
My first guess would be container foreground process (some mq process) quits for some reason and then container stops. 
Can you check if container with exact same options run from docker command line client keep working and does not stop by himself ?

Btw, 
Rule logs many information via slf4j logging framework (including containers stdout and stderr).
Seeing them would really help diagnose what's going on.
Do you need quick example how to add logging config ?

**Comment by tdomzal** [comment]
After adding simple logging config:
https://github.com/tdomzal/miniature-queue/commit/7021f7b5cda36d44d950ef131194a178058b3e7b

I ran FanoutTest test and this is output log.
You can see container output lines prefixed with '296fbb23aaf1-stdout'.

```
21:22:50.043 DEBUG pl.domzal.junit.docker.rule.DockerRule - image 'ibmcom/mqlight:1.0' found
21:22:50.048 INFO  com.spotify.docker.client.DefaultDockerClient - Creating container with ContainerConfig: ContainerConfig{hostname=null, domainname=null, username=null, attachStdin=null, attachStdout=null, attachStderr=null, portSpecs=null, exposedPorts=null, tty=null, openStdin=null, stdinOnce=null, env=[LICENSE=accept, volume=/var/example:/var/mqlight, MQLIGHT_USER=user, MQLIGHT_PASSWORD=password, publish=5672:5672, publish=9180:9180], cmd=null, image=ibmcom/mqlight:1.0, volumes=null, workingDir=null, entrypoint=null, networkDisabled=false, onBuild=null, labels=null, macAddress=null, hostConfig=HostConfig{binds=null, containerIDFile=null, lxcConf=null, privileged=null, portBindings=null, links=null, publishAllPorts=false, dns=null, dnsSearch=null, extraHosts=null, volumesFrom=null, networkMode=null, securityOpt=null, memory=null, memorySwap=null, cpuShares=null, cpusetCpus=null, cpuQuota=null, cgroupParent=null, restartPolicy=null}, stopSignal=null}
21:22:50.334 INFO  pl.domzal.junit.docker.rule.DockerRule - container ibmcom/mqlight:1.0 created, id 296fbb23aaf1c80e3954b79fa4515454c41ca2552ee01872add4321954d6152c, short id 296fbb23aaf1
21:22:50.335 DEBUG pl.domzal.junit.docker.rule.DockerRule - rule before 296fbb23aaf1
21:22:50.335 INFO  com.spotify.docker.client.DefaultDockerClient - Starting container with Id: 296fbb23aaf1c80e3954b79fa4515454c41ca2552ee01872add4321954d6152c
21:22:50.610 DEBUG pl.domzal.junit.docker.rule.DockerRule - 296fbb23aaf1 started
21:22:50.742 INFO  pl.domzal.junit.docker.rule.DockerRule - 296fbb23aaf1 waiting for log message '### Welcome to IBM MQ Light ###'
21:22:50.743 DEBUG pl.domzal.junit.docker.rule.WaitForUnit - wait... - started (90000ms)
296fbb23aaf1-stdout> Initializing IBM MQ Light
296fbb23aaf1-stderr> + mqlight-config -v
296fbb23aaf1-stderr> + mqlight-config --accept-license --user user --password password
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> Licensed Materials - Property of IBM 
296fbb23aaf1-stdout>                  
296fbb23aaf1-stdout>  5725-P60 
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout>  (C) Copyright IBM Corporation 1994, 2015 
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> US Government Users Restricted Rights - Use, duplication or disclosure
296fbb23aaf1-stdout> restricted by GSA ADP Schedule Contract with IBM Corp.
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> Name:        IBM MQ Light
296fbb23aaf1-stdout> Version:     1.0.2.0
296fbb23aaf1-stdout> Level:       p800-L151130.2
296fbb23aaf1-stdout> BuildType:   IKAP - (Production)
296fbb23aaf1-stdout> O/S:         Linux 4.1.19-boot2docker
296fbb23aaf1-stdout> InstPath:    /opt/mqlight/runtime
296fbb23aaf1-stdout> DataPath:    /var/mqlight/mqm
296fbb23aaf1-stdout> LicenseType: Developer
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> Licensed Materials - Property of IBM 
296fbb23aaf1-stdout>                  
296fbb23aaf1-stdout>  5725-P60 
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout>  (C) Copyright IBM Corporation 1994, 2015 
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> US Government Users Restricted Rights - Use, duplication or disclosure
296fbb23aaf1-stdout> restricted by GSA ADP Schedule Contract with IBM Corp.
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> License agreement accepted.
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> MQ Light configuration settings updated to:
296fbb23aaf1-stdout>   Configuration Path             : /var/mqlight
296fbb23aaf1-stdout>   User name and password security: enabled (user name: user)
296fbb23aaf1-stdout>   SSL/TLS security               : disabled
296fbb23aaf1-stdout>   Server port                    : 5672
296fbb23aaf1-stdout>   Web UI port                    : 9180
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> Changes will apply next time mqlight-start is run.
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> Licensed Materials - Property of IBM 
296fbb23aaf1-stdout>                  
296fbb23aaf1-stdout>  5725-P60 
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout>  (C) Copyright IBM Corporation 1994, 2015 
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> US Government Users Restricted Rights - Use, duplication or disclosure
296fbb23aaf1-stdout> restricted by GSA ADP Schedule Contract with IBM Corp.
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> 
296fbb23aaf1-stderr> + mqlight-start --no-browser
21:23:18.965 DEBUG pl.domzal.junit.docker.rule.WaitForUnit - wait... - condition met in 28154 ms
21:23:18.966 DEBUG pl.domzal.junit.docker.rule.DockerRule - 296fbb23aaf1 message '### Welcome to IBM MQ Light ###' found
21:23:18.966 INFO  pl.domzal.junit.docker.rule.DockerRule - 296fbb23aaf1 docker host: 192.168.99.100, ip: 172.17.0.2, gateway: 172.17.0.1, exposed ports: {5671/tcp=null, 5672/tcp=null, 9180/tcp=null, 9181/tcp=null}
21:23:19.095 INFO  com.github.oxo42.stateless4j.StateMachine - Firing EP_RESP_OK
21:23:19.296 INFO  com.github.oxo42.stateless4j.StateMachine - Firing START
21:23:19.299 INFO  com.github.oxo42.stateless4j.StateMachine - Firing EP_RESP_OK
21:23:19.300 INFO  com.github.oxo42.stateless4j.StateMachine - Firing START
maj 13, 2016 9:23:19 PM com.github.mrchris2000.queue.mqlight.implementation.MqLightServerImplementation listen
INFO: Registering listener
maj 13, 2016 9:23:19 PM com.github.mrchris2000.queue.mqlight.implementation.MqLightServerImplementation listen
INFO: Registering listener
296fbb23aaf1-stdout> Starting MQ Light..................
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> ### Welcome to IBM MQ Light ###
296fbb23aaf1-stdout> MQ Light UI running at http://localhost:9180
296fbb23aaf1-stdout> MQ Light Server ready to use at amqp://localhost:5672
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> License Type: Developer - you are running a developer version of MQ Light. An upgrade to the Production license is recommended to obtain support for use in production systems.
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> Please leave feedback at http://ibm.biz/mqlight-forum
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> ----------------------------------------
296fbb23aaf1-stdout> Monitoring MQ Light...
296fbb23aaf1-stdout> QMNAME(DEFAULT)                                           STATUS(Running)
21:23:19.952 DEBUG pl.domzal.junit.docker.rule.DockerRule - after 296fbb23aaf1
21:23:20.301 INFO  com.github.oxo42.stateless4j.StateMachine - Firing OPEN_RESP_RETRY
21:23:20.302 INFO  com.github.oxo42.stateless4j.StateMachine - Firing EP_RESP_EXHAUSTED
21:23:20.303 INFO  com.github.oxo42.stateless4j.StateMachine - Firing OPEN_RESP_RETRY
21:23:20.304 INFO  com.github.oxo42.stateless4j.StateMachine - Firing EP_RESP_EXHAUSTED
21:23:21.038 DEBUG pl.domzal.junit.docker.rule.DockerRule - 296fbb23aaf1 state ContainerState{running=true, pid=11220, paused=false, restarting=false, exitCode=0, startedAt=Fri May 13 21:22:50 CEST 2016, finishedAt=Sat Jan 01 01:00:00 CET 1, error=, oomKilled=false}
21:23:21.158 INFO  com.github.oxo42.stateless4j.StateMachine - Firing TIMER_RESP_POP
21:23:21.158 INFO  com.github.oxo42.stateless4j.StateMachine - Firing EP_RESP_OK
21:23:21.248 INFO  com.github.oxo42.stateless4j.StateMachine - Firing TIMER_RESP_POP
21:23:21.249 INFO  com.github.oxo42.stateless4j.StateMachine - Firing EP_RESP_OK
21:23:22.177 INFO  com.github.oxo42.stateless4j.StateMachine - Firing OPEN_RESP_RETRY
21:23:22.178 INFO  com.github.oxo42.stateless4j.StateMachine - Firing EP_RESP_EXHAUSTED
21:23:22.252 INFO  com.github.oxo42.stateless4j.StateMachine - Firing OPEN_RESP_RETRY
21:23:22.252 INFO  com.github.oxo42.stateless4j.StateMachine - Firing EP_RESP_EXHAUSTED
21:23:23.705 INFO  com.github.oxo42.stateless4j.StateMachine - Firing TIMER_RESP_POP
21:23:23.706 INFO  com.github.oxo42.stateless4j.StateMachine - Firing EP_RESP_OK
21:23:24.204 INFO  com.github.oxo42.stateless4j.StateMachine - Firing TIMER_RESP_POP
21:23:24.204 INFO  com.github.oxo42.stateless4j.StateMachine - Firing EP_RESP_OK
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> Licensed Materials - Property of IBM 
296fbb23aaf1-stdout>                  
296fbb23aaf1-stdout>  5725-P60 
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout>  (C) Copyright IBM Corporation 1994, 2015 
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> US Government Users Restricted Rights - Use, duplication or disclosure
296fbb23aaf1-stdout> restricted by GSA ADP Schedule Contract with IBM Corp.
296fbb23aaf1-stdout> 
296fbb23aaf1-stdout> 
21:23:24.728 INFO  com.github.oxo42.stateless4j.StateMachine - Firing OPEN_RESP_RETRY
21:23:24.728 INFO  com.github.oxo42.stateless4j.StateMachine - Firing EP_RESP_EXHAUSTED
21:23:25.206 INFO  com.github.oxo42.stateless4j.StateMachine - Firing OPEN_RESP_RETRY
21:23:25.206 INFO  com.github.oxo42.stateless4j.StateMachine - Firing EP_RESP_EXHAUSTED
21:23:26.501 INFO  pl.domzal.junit.docker.rule.DockerRule - 296fbb23aaf1 stopped

java.lang.AssertionError
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.github.mrchris2000.queue.mqlight.example.FanoutTest.whenItemPutOnQueueThenAllListenersRelieveACopy(FanoutTest.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by tdomzal** [comment]
Container is closed from rule 'after' method - it means only after test case code finishes.
Stack trace in log is **after** container close event only because junit reports failure diagnostics at the end. 
So my assumption would be sequence of events is like this:
- test case assertions are not fulfilled (during time given for test), 
- test finishes, 
- rule closes docker container

**Comment by mrchris2000** [comment]
Thanks for the input, just got this resolved.
It needed a couple of changes (not least because the 'wait for' log line didn't quite indicate system readiness).

I think the trick was switching to publishAllPorts = true and pulling the dynamic port back to use in the test, I was seeing odd nic binding behaviour without using AllPorts:
5671-5672/tcp
Versus this which works:
0.0.0.0:5672->5672/tcp

Entirely sure this is due to my inexperience with using Docker; but it works now :)

**Comment by tdomzal** [comment]
Great you figured it out!

And thanks for using junit-docker-rule - I'm glad you are finding it usefull :).
