### ISSUE TITLE
Images using ENTRYPOINT will not start when builder.entrypoint(..) is not set

### ISSUE THREAD

**Issue by tdomzal** [tdomzal/junit-docker-rule#43]
Version 0.4.
Test case:

```
package pl.domzal.junit.docker.rule.regression;

import org.junit.Rule;
import org.junit.Test;

import pl.domzal.junit.docker.rule.DockerRule;

public class Bug42 {

    @Rule
    public final DockerRule toxicContainer = DockerRule.builder()
            .imageName("shopify/toxiproxy")
            // commenting out this line will make it work as expected
            //.entrypoint("/go/bin/toxiproxy")
            .build();

    @Test
    public void shouldStart() {
    }

}

```
ends with error:

```
java.lang.IllegalStateException: {"message":"oci runtime error: container_linux.go:265: starting container process caused \"exec: \\\"-host=0.0.0.0\\\": executable file not found in $PATH\"\n"}
	at pl.domzal.junit.docker.rule.DockerRule.before(DockerRule.java:156)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	...
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST https://192.168.99.100:2376/containers/55aeec9f3c2b3b92ee89e0636fdd125040fe1f39100c73c96f2a22eab2b09f9b/start: 400, body: {"message":"oci runtime error: container_linux.go:265: starting container process caused \"exec: \\\"-host=0.0.0.0\\\": executable file not found in $PATH\"\n"}
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2691)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2652)
	...
Caused by: javax.ws.rs.BadRequestException: HTTP 400 Bad Request
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:999)

```

**Comment by tdomzal** [comment]
0.4 upgraded docker client dependency from 6.1.1 to 8.9.2.
and looks like this commit:
https://github.com/spotify/docker-client/commit/a89b43bfb7c7738b8cd76128dc00126dec3b007e
changed treating 'empty' entrypoint values (null vs. empty string table).

In effect:
- default empty docker rule `entrypoint` value (zero-sized string table) 'zeroes' image entrypoint definition
- first segment of `cmd` is treated as command (`executable file not found` in test case above)
