### ISSUE TITLE
NoClassDefFoundError: org/glassfish/hk2/api/MultiException

### ISSUE THREAD

**Issue by nkonev** [tdomzal/junit-docker-rule#44]
```
    @ClassRule
    public static DockerRule postgresRule = DockerRule.builder()
            .imageName("postgres:9.5.13")
            .waitFor(WaitFor.logMessageSequence(
                    "waiting for server to shut down",
                    "database system is ready to accept connections."
            ))
            .build();
```

causes
```
java.lang.NoClassDefFoundError: org/glassfish/hk2/api/MultiException

	at pl.domzal.junit.docker.rule.DockerRule.<init>(DockerRule.java:81)
	at pl.domzal.junit.docker.rule.DockerRuleBuilder.build(DockerRuleBuilder.java:51)
	at my.company.tests.it.BaseIntegrationTest.<clinit>(BaseIntegrationTestTemplate.java:67)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at org.junit.runners.model.FrameworkField.get(FrameworkField.java:73)
	at org.junit.runners.model.TestClass.getAnnotatedFieldValues(TestClass.java:230)
	at org.junit.runners.ParentRunner.classRules(ParentRunner.java:255)
	at org.junit.runners.ParentRunner.withClassRules(ParentRunner.java:244)
	at org.junit.runners.ParentRunner.classBlock(ParentRunner.java:194)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:362)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: org.glassfish.hk2.api.MultiException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more
```

**Comment by tdomzal** [comment]
Two questions:
Which version of junit-docker-rule are you using ?
Do you use it with spring-boot 2.0.x ?

**Comment by nkonev** [comment]
`Do you use it with spring-boot 2.0.x ?` yes
`Which version of junit-docker-rule are you using` latest

**Comment by tdomzal** [comment]
Please see #42.

**Comment by tdomzal** [comment]
Assuming fixed using workaround (unfortunately, this is external dependency issue) described in #42.
